run_name: one-billion-6
seed: 42
dry_run: false
distributed_strategy: fsdp

wandb:
  name: ${run_name}
  project: mc-2
  entity: jchooi

custom_train_dataset: true
custom_data_config:
  custom_data_type: markov
  epoch_size: 1_000_000_000
  markov_dataset_config:
    num_states: 3
    seq_len: 2048
    vocab_size: 10

model:
  d_model: 1024
  n_heads: 1
  n_layers: 2
  mlp_ratio: 8
  alibi: false
  rope: true
  alibi_bias_max: 8.0
  flash_attention: false
  attention_dropout: 0.05
  attention_layer_norm: true
  multi_query_attention: true
  block_type: sequential
  layer_norm_type: low_precision  # if not compiling, use 'low_precision'
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 2048
  include_bias: true
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 50279
  pad_token_id: 1
  init_device: meta
  init_std: 0.02

compile: null  # causes instability on AMD GPUs
# compile:
#   mode: default

optimizer:
  name: adamw
  learning_rate: 4.0e-4
  weight_decay: 0.01
  betas:
  - 0.9
  - 0.95

scheduler:
  name: cosine_with_warmup
  t_warmup: 2000
  alpha_f: 0.1

data:
  pad_direction: right
  num_workers: 8
  drop_last: true
  pin_memory: true
  prefetch_factor: 4
  persistent_workers: true
  timeout: 0

tokenizer:
  identifier: ../olmo_data/tokenizers/allenai_eleuther-ai-gpt-neox-20b-pii-special.json
  truncate_direction: right

save_folder: /n/holyscratch01/sham_lab/summer_2024/checkpoints/${run_name}-${oc.env:SLURM_JOB_ID}
save_overwrite: false
# Sharded checkpoints (best for restarts)
save_interval: 1000
save_num_checkpoints_to_keep: 9
# Unsharded checkpoints (for final storage)
save_interval_unsharded: 1000
save_num_unsharded_checkpoints_to_keep: -1

load_path: null

# max_duration: 476837  # 2T tokens
max_duration: 3ep  # 3T tokens
global_train_batch_size: 256
device_train_microbatch_size: 12

precision: amp_bf16
  
max_grad_norm: 1.0

speed_monitor:
  window_size: 20

eval_interval: 250
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  #########################
  # Perplexity evaluations #
  #########################
  - label: mc-bigram-validation
    type: bg
    subset_num_batches: 2
    data:
      num_workers: 1
      drop_last: true
      pin_memory: true
      persistent_workers: true
      prefetch_factor: 4
  - label: mc-unigram-validation
    type: ug
    subset_num_batches: 2
    data:
      num_workers: 1
      drop_last: true
      pin_memory: true
      persistent_workers: true
      prefetch_factor: 4
  - label: mc-uniform-validation
    type: uf
    subset_num_batches: 2
    data:
      num_workers: 1
      drop_last: true
      pin_memory: true
      persistent_workers: true
      prefetch_factor: 4